version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    build: ./backend
    ports:
      - "8001:80"  # こちらは正しい
    volumes:
      - ./backend/public:/var/www/html # ←修正後の設定（正解）

